project_id = "idkzlnzvqzqvkdchchnz"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = false
  [functions.send-demo-validation]
    verify_jwt = false
  [functions.activate-purchase]
    verify_jwt = false
  [functions.request-purchase]
    verify_jwt = false
  [functions.verify-purchase]
    verify_jwt = false
